sudo: required
services:
  - docker

before_install:
  - docker build -t bauwie/cra-dockerized -f Dockerfile.dev .

script:
  - docker run -e CI=true bauwie/cra-dockerized npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'cra-dockerized'
  env: 'CraDockerized-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-082292442293'
  bucket_path: 'cra-dockerized'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
